### ISSUE TITLE
Swift 5.7?

### ISSUE THREAD

**Issue by kylebrowning** [apple/swift-format#381]
The 5.7 branch fails to build so im curious when we will see a release for 5.7 so that those of us testing on Ventura / Xcode 14 can swift-format

**Comment by kylebrowning** [comment]
Additionally building manually fails from `main` and `release/5.7`

```
swift-format on  main via 🐍 v2.7.16 via 🏎  v5.7
❯ swift build
Building for debugging...
/Users/kylebrowning/Projects/swift/swift-format/.build/checkouts/swift-syntax/Sources/SwiftSyntaxParser/SyntaxParser.swift:150:9: error: cannot find 'swiftparse_parser_set_language_version' in scope
        swiftparse_parser_set_language_version(c_parser, languageVersionCString)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/kylebrowning/Projects/swift/swift-format/.build/checkouts/swift-syntax/Sources/SwiftSyntaxParser/SyntaxParser.swift:154:7: error: cannot find 'swiftparse_parser_set_enable_bare_slash_regex_literal' in scope
      swiftparse_parser_set_enable_bare_slash_regex_literal(c_parser, enableBareSlashRegexLiteral)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[7/20] Archiving libSwiftSyntax.a
````

**Comment by kkk669** [comment]
The `release/5.7` branch can be built using Swift that bundled in Xcode 14 beta 3.

**Comment by JetA2** [comment]
I'm getting the same errors when trying to build 5.6:

```
VERSION=0.50600.1  # replace this with the version you need
git clone https://github.com/apple/swift-format.git
cd swift-format
git checkout "tags/$VERSION"
swift build -c release

swift-format/.build/checkouts/swift-syntax/Sources/SwiftSyntaxParser/SyntaxParser.swift:150:9: error: cannot find 'swiftparse_parser_set_language_version' in scope
        swiftparse_parser_set_language_version(c_parser, languageVersionCString)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
swift-format/.build/checkouts/swift-syntax/Sources/SwiftSyntaxParser/SyntaxParser.swift:154:7: error: cannot find 'swiftparse_parser_set_enable_bare_slash_regex_literal' in scope
      swiftparse_parser_set_enable_bare_slash_regex_literal(c_parser, enableBareSlashRegexLiteral)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

swift --version                                            
swift-driver version: 1.45.2 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)
Target: x86_64-apple-macosx12.0

**Comment by kylebrowning** [comment]
@kkk669 I am on that branch and it does not compile

**Comment by damuellen** [comment]
`/workspaces/swift-format (release/5.7) $ swift --version`
`Swift version 5.7-dev (LLVM d5f117e38620783, Swift 260a80fcce5a2ab)
Target: x86_64-unknown-linux-gnu`

`@damuellen ➜ /workspaces/swift-format (release/5.7) $ swift build -c release --product swift-format
Building for production...`
`[16/18] Compiling TSCBasic Await.swift`
`/workspaces/swift-format/Sources/SwiftFormatCore/RuleMask.swift:133:3: error: 'super.init' isn't called on all paths before returning from initializer
  }`
`/workspaces/swift-format/Sources/SwiftFormatCore/SyntaxLintRule.swift:30:3: error: 'super.init' isn't called on all paths before returning from initializer
  }`

The 5.7 branch fails to build under Linux with newest snapshot.

**Comment by soumyamahunt** [comment]
Waiting for this as well, after moving some of my protocols with associated types to primary associated types I am getting the following error with the latest release:

> error: protocols do not allow generic parameters; use associated types instead

**Comment by evgzor** [comment]
@allevato 5.7 is not compiling

**Comment by allevato** [comment]
This is currently waiting on https://github.com/apple/swift-syntax/issues/787 so that we have a matching swift-syntax version.

**Comment by allevato** [comment]
I've updated the `release/5.7` branch with a temporary reference to swift-syntax's `swift-5.7-RELEASE` tag in https://github.com/apple/swift-format/pull/397. Note the caveat about manually setting the rpath in the description of that PR.

When swift-syntax 0.50700.0 is released, I'll update this repo again to use the semver dependency and cut a release.

**Comment by allevato** [comment]
https://github.com/apple/swift-format/releases/tag/0.50700.0 is now published.

**Comment by NSCoder** [comment]
@allevato I'm still seeing this on `0.50700.0`

**Comment by allevato** [comment]
Can you provide some details about your build environment?

**Comment by mrstegeman** [comment]
Seeing it when trying to build in Ubuntu 22.04 for Homebrew:

https://github.com/Homebrew/homebrew-core/actions/runs/3095751529/jobs/5010578616

**Comment by mrstegeman** [comment]
Seeing it when trying to build in Ubuntu 22.04 for Homebrew:

https://github.com/Homebrew/homebrew-core/actions/runs/3095751529/jobs/5010578616

**Comment by allevato** [comment]
What version of Swift is used in that image? I wasn't able to find it in the logs. Are you sure that it's 5.7?

**Comment by mrstegeman** [comment]
I think it's probably running 5.6.3. Guess that'll need to be updated first.

**Comment by michaellenaghan** [comment]
@allevato  This morning I did a `git pull`, a `swift package reset`, and a `swift build -c release`. I'm still seeing the problem:

```
swift-format --version
dyld[30455]: Library not loaded: '@rpath/lib_InternalSwiftSyntaxParser.dylib'
  Referenced from: '/usr/local/bin/swift-format'
  Reason: tried: '/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/local/bin/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/local/bin/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/local/lib/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/lib/lib_InternalSwiftSyntaxParser.dylib' (no such file)
fish: Job 1, 'swift-format --version' terminated by signal SIGABRT (Abort)
```

I'm on a Mac. Here's my `swift` version:

```
swift --version
swift-driver version: 1.62.8 Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)
Target: x86_64-apple-macosx12.0
```

What else could I provide?

(Still poking around to see if there's something I missed...)

**Comment by allevato** [comment]
Which tag did you pull?

The error you're seeing looks like one that would occur if the binary distribution of `lib_InternalSwiftSyntaxParser.dylib` in swift-syntax wasn't being retrieved properly, forcing it to look in the default rpaths instead.

**Comment by michaellenaghan** [comment]
I don't know if this helps, but it works if I run it from the build directory:

```
./.build/release/swift-format --version
0.50700.0
```

It doesn't if I copy it to `/usr/local/bin` and run it from there.

**Comment by michaellenaghan** [comment]
I'm at the head of `release/5.7`.

**Comment by allevato** [comment]
> It doesn't if I copy it to /usr/local/bin and run it from there.

Ah-ha, that's the problem, then; you also need to copy `lib_InternalSwiftSyntaxParser.dylib` along with it or `dyld` won't be able to find it since it's no longer in the same directory nor on any of the other library paths.

**Comment by michaellenaghan** [comment]
Btw, I was in a rush 'cause I was heading into a meeting; meant to add: thank you for your help!
