### ISSUE TITLE
Swift-format fails to build with 5.7 toolchain

### ISSUE THREAD

**Issue by GeorgeLyon** [apple/swift-format#389]
The errors are:
```
SwiftFormatCore/SyntaxLintRule.swift:30:3: error: 'super.init' isn't called on all paths before returning from initializer
SwiftFormatCore/RuleMask.swift:133:3: error: 'super.init' isn't called on all paths before returning from initializer
```

It looks like the no-argument `init` for `SyntaxVisitor` has been deprecated and this is causing issues with the auto-super-init call for subclasses. It seems we need to pick a `ViewMode` for these, either `fixedUp` or `sourceAccurate` and I'm not sure which one would be correct for the `swift-format` use case. If someone has an idea of how to think about this, I'd be happy to throw together a patch.

**Comment by realityworks** [comment]
Which version of the Xcode toolchain are you using?

Works fine for me on Xcode 14 beta 4.

All that appears are the following warnings : 

```
/Applications/Xcode-14-beta-4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGAffineTransform.h:161:1: warning: imported declaration 'CGAffineTransformDecompose' could not be mapped to 'CGAffineTransformComponents.decomposed(self:)'
CF_SWIFT_NAME(CGAffineTransformComponents.decomposed(self:))
^
/Applications/Xcode-14-beta-4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGAffineTransform.h:161:1: note: please report this issue to the owners of 'CoreGraphics'
CF_SWIFT_NAME(CGAffineTransformComponents.decomposed(self:))
^
/Applications/Xcode-14-beta-4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGAffineTransform.h:169:1: warning: imported declaration 'CGAffineTransformMakeWithComponents' could not be mapped to 'CGAffineTransformComponents.init(_:)'
CF_SWIFT_NAME(CGAffineTransformComponents.init(_:))
^
/Applications/Xcode-14-beta-4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGAffineTransform.h:169:1: note: please report this issue to the owners of 'CoreGraphics'
CF_SWIFT_NAME(CGAffineTransformComponents.init(_:))
^

```

**Comment by realityworks** [comment]
Actually, trying to run a build with the latest toolchain results in this :

```
dyld[24048]: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
  Referenced from: <51F5C555-656D-395C-804A-0083E32D4FD3> /Users/piotrsuwara/Developer/brownwatson/swift-format/swift-format
  Reason: tried: '/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Users/piotrsuwara/Developer/brownwatson/swift-format/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Applications/Xcode-14-beta-5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-14-beta-5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Users/piotrsuwara/Developer/brownwatson/swift-format/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Applications/Xcode-14-beta-5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-14-beta-5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS@rpath/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Users/piotrsuwara/Developer/brownwatson/swift-format/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Applications/Xcode-14-beta-5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-14-beta-5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Users/piotrsuwara/Developer/brownwatson/swift-format/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Applications/Xcode-14-beta-5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode-14-beta-5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/local/lib/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/lib/lib_InternalSwiftSyntaxParser.dylib' (no such file, not in dyld cache)
```

I'm going to leave it for our new project and wait until swift 5.7 is fully supported.

**Comment by kylebrowning** [comment]
duplicate of #381

**Comment by realityworks** [comment]
> I'm on beta 5, it may be relevant that I'm trying to build on Ventura.

I am also on Ventura. Beta 5 of Xcode and OS.

**Comment by allevato** [comment]
Consolidating this into https://github.com/apple/swift-format/issues/381.
